version: '3.8'
services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile.rails
    ports:
      - "80:3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=production
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp_production 
volumes:
  postgres_data:
